compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  rps:
    npmAlwaysAuth: false
    npmPublishRegistry: 'https://npmjs.rpso.in'
    npmRegistryServer: 'https://npmjs.rpso.in'

yarnPath: .yarn/releases/yarn-4.0.2.cjs
