nodeLinker: node-modules

npmScopes:
  rps:
    npmAlwaysAuth: false
    npmPublishRegistry: "https://npmjs.rpso.in"
    npmRegistryServer: "https://npmjs.rpso.in"

yarnPath: .yarn/releases/yarn-3.4.1.cjs